MACHINES = {
    :lvm => {
        :box_name => "centos/7",
        :cpus => 2,
        :memory => 1024,
    }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.box_check_update = false
    config.vm.define boxname do |box|
    box.vm.box = boxconfig[:box_name]
    config.vm.box_url = "https://cloud.centos.org/centos/7/vagrant/x86_64/images/CentOS-7-x86_64-Vagrant-1804_02.VirtualBox.box"
    box.vm.host_name = boxname.to_s

    box.vm.provider :virtualbox do |v|
        v.cpus = boxconfig[:cpus]
        v.memory = boxconfig[:memory]
    end

    box.vm.provision "shell", path: "script.sh"
    end
  end
end